# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0abea14d633cc78b0c81fc13be8497aa"
name = "deployment-test"
handle = "deployment-test-6"
application_url = "https://mitsubishi-polyester-extensions-models.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c4e86bd7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://mitsubishi-polyester-extensions-models.trycloudflare.com/auth/callback",
  "https://mitsubishi-polyester-extensions-models.trycloudflare.com/auth/shopify/callback",
  "https://mitsubishi-polyester-extensions-models.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
